//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D2L.CodeStyle.Analyzers.Specs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpecTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D2L.CodeStyle.Analyzers.Specs.SpecTests", typeof(SpecTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // analyze with: RpcDependencyAnalyzer
        /// 
        ///using System;
        ///using D2L.LP.Extensibility.Activation.Domain;
        ///using D2L.Web;
        ///using D2L.Web.RequestContext;
        ///
        ///namespace D2L.Web {
        ///	public interface IRpcContext { }
        ///	public interface IRpcPostContext { }
        ///	public class RpcAttribute : Attribute { }
        ///}
        ///
        ///namespace D2L.Web.RequestContext {
        ///	public interface IRpcPostContextBase { }
        ///}
        ///
        ///namespace D2L.LP.Extensibility.Activation.Domain {
        ///	public class DependencyAttribute : Attribute { }
        ///}
        ///
        ///namespace D2L.CodeStyl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RpcAnalyzer {
            get {
                return ResourceManager.GetString("RpcAnalyzer", resourceCulture);
            }
        }
    }
}
